COMMAND_COMPLETED_SUCCESSFULLY = 200
DOMAIN_NAME_AVAILABLE = 210
DOMAIN_NAME_NOT_AVAILABLE = 211
NAME_SERVER_AVAILABLE = 212
NAME_SERVER_NOT_AVAILABLE = 213
CONTACT_AVAILABLE = 214
CONTACT_NOT_AVAILABLE = 215
OBJECT_AVAILABLE = 216
OBJECT_NOT_AVAILABLE = 217
REQUEST_AVAILABLE = 218
REQUEST_NOT_AVAILABLE = 219
COMMAND_COMPLETED_SUCCESSFULLY_CLOSING_CONNECTION = 220

SERVER_ERROR_CLOSING_CONNECTION = 420  # Blaze it
SERVER_ERROR_CLIENT_SHOULD_TRY_AGAIN = 421
ABUSE_DETECTED = 422
SOCKET_ERROR = 423

INVALID_COMMAND_NAME = 500
INVALID_COMMAND_OPTION = 501
INVALID_ENTITY_VALUE = 502
INVALID_ATTRIBUTE_NAME = 503
MISSING_REQUIRED_ATTRIBUTE = 504
INVALID_ATTRIBUTE_VALUE_SYNTAX = 505
INVALID_OPTION_VALUE = 506
INVALID_COMMAND_FORMAT = 507
MISSING_REQUIRED_ENTITY = 508
MISSING_COMMAND_OPTION = 509

SERVER_CLOSING_CONNECTION_TRY_AGAIN = 520
TOO_MANY_SESSIONS_OPEN_CLOSING_CONNECTION = 521

AUTHENTICATION_FAILED = 530
AUTHORIZATION_FAILED = 531
DOMAIN_NAMES_LINKED_WITH_NAME_SERVER = 532
DOMAIN_NAME_HAS_ACTIVE_NAME_SERVERS = 533
DOMAIN_NAME_NOT_FLAGGED_FOR_TRANSFER = 534
RESTRICTED_IP_ADDRESS = 535
DOMAIN_ALREADY_FLAGGED_FOR_TRANSFER = 536

ATTRIBUTE_VALUE_NOT_UNIQUE = 540
INVALID_ATTRIBUTE_VALUE = 541
INVALID_OLD_ATTRIBUTE_VALUE = 542
FINAL_OR_IMPLICIT_ATTRIBUTE_CANNOT_BE_UPDATED = 543
ENTITY_ON_HOLD = 544
ENTITY_REFERENCE_NOT_FOUND = 545
CREDIT_LIMIT_EXCEEDED = 546
INVALID_COMMAND_SEQUENCE = 547
DOMAIN_NOT_UP_FOR_RENEWAL = 548
COMMAND_FAILED = 549
PARENT_DOMAIN_NOT_REGISTERED = 550
PARENT_DOMAIN_STATUS_DOES_NOT_ALLOW_OPERATION = 551
DOMAIN_STATUS_DOES_NOT_ALLOW_OPERATION = 552
OPERATION_NOT_ALLOWED_DOMAIN_PENDING_TRANSFER = 553
DOMAIN_ALREADY_REGISTERED = 554
DOMAIN_ALREADY_RENEWED = 555
MAXIMUM_REGISTRATION_PERIOD_EXCEEDED = 556
OBJECT_STATUS_PROHIBITS_OPERATION = 557

RESOURCE_DISABLED = 560
RESOURCE_STILL_IN_USE = 561
EMAIL_ADDRESS_ALREADY_USES_FORWARDING = 562
EMAIL_ADDRESS_ALREADY_USES_MAILSPACE = 563
EMAIL_DOMAIN_ALREADY_LINKED_TO_DIFFERENT_MAILSPACE = 564
